### ISSUE TITLE
Readme file understanding

### ISSUE THREAD

**Issue by KrickGregory** [chiahsing/nest_hub#1]
Hey;

Maybe a very stupid question but in your readme file you write 
"Create a nest_hub folder under /config/pyscript/apps/, and put __init__.py in it. Then, in pyscript's [configuration](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#configuration), add the following section:"
But : some people and I don't understand where to make the nest_hub directory. 
Is it possible to explain some more ?

Grts Gregory

**Comment by chiahsing** [comment]
/config is your home assistant configuration folder. I guess you need to create the folders if they are missing. Basically, the script goes under /config/pyscript/apps/nest_hub/. If this still doesn't work, you may want to refer to pyscript's document to see how to get it to work in your case. This script just needs to be configured as an app of pyscript.

**Comment by KrickGregory** [comment]
Thanks for the quick answer. I'm investigating it right now but have to leave home in half an hour so will look deeper tomorrow. I'll notify about my taken steps then for other people looking for this.

**Comment by KrickGregory** [comment]
Didn't get it to work. But I found out it is in the new HA standard now. Thanks.

**Comment by chiahsing** [comment]
So I checked it a bit. You would have to create folder `pyscript` under `/config` if you haven't done that before. And then create `apps` under `pyscript`. You can check if a script is loaded successfully from the log by adding the following to your HA config:

```
pyscript:
  apps:
    nest_hub:

logger:
  default: warning
  logs:
    custom_components.pyscript: info
```

When you click `LOAD FULL LOGS`, uou should be able to see something like this
`2023-02-05 10:02:48.813 INFO (MainThread) [custom_components.pyscript.global_ctx] Reloaded /config/pyscript/apps/nest_hub/__init__.py`
